// <auto-generated />
using System;
using BBBWebApiCodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BBBWebApiCodeFirst.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190207104325_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", "'postgis', '', ''")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.Age", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("Ages");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.Day", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.Gender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.Mtc", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<Geometry>("geom");

                    b.Property<int>("groesse");

                    b.HasKey("id");

                    b.ToTable("Mtcs");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcActivity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("day");

                    b.Property<decimal?>("density");

                    b.Property<int>("hour");

                    b.Property<int>("people");

                    b.Property<long>("zone");

                    b.HasKey("id");

                    b.HasIndex("day");

                    b.HasIndex("zone");

                    b.ToTable("MtcActivitys");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcAge", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("age");

                    b.Property<int>("day");

                    b.Property<decimal>("fraction");

                    b.Property<int>("hour");

                    b.Property<long>("zone");

                    b.HasKey("id");

                    b.HasIndex("age");

                    b.HasIndex("day");

                    b.HasIndex("zone");

                    b.ToTable("MtcAges");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcGender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("day");

                    b.Property<decimal>("fraction");

                    b.Property<int>("gender");

                    b.Property<int>("hour");

                    b.Property<long>("zone");

                    b.HasKey("id");

                    b.HasIndex("day");

                    b.HasIndex("gender");

                    b.HasIndex("zone");

                    b.ToTable("MtcGenders");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcHomezone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("day");

                    b.Property<decimal>("fraction");

                    b.Property<long>("homezone");

                    b.Property<long>("zone");

                    b.HasKey("id");

                    b.HasIndex("day");

                    b.HasIndex("zone");

                    b.ToTable("MtcHomezones");
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcActivity", b =>
                {
                    b.HasOne("BBBWebApiCodeFirst.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("day")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BBBWebApiCodeFirst.Models.Mtc", "Mtc")
                        .WithMany()
                        .HasForeignKey("zone")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcAge", b =>
                {
                    b.HasOne("BBBWebApiCodeFirst.Models.Age", "Age")
                        .WithMany()
                        .HasForeignKey("age")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BBBWebApiCodeFirst.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("day")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BBBWebApiCodeFirst.Models.Mtc", "Mtc")
                        .WithMany()
                        .HasForeignKey("zone")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcGender", b =>
                {
                    b.HasOne("BBBWebApiCodeFirst.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("day")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BBBWebApiCodeFirst.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("gender")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BBBWebApiCodeFirst.Models.Mtc", "Mtc")
                        .WithMany()
                        .HasForeignKey("zone")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BBBWebApiCodeFirst.Models.MtcHomezone", b =>
                {
                    b.HasOne("BBBWebApiCodeFirst.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("day")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BBBWebApiCodeFirst.Models.Mtc", "Mtc")
                        .WithMany()
                        .HasForeignKey("zone")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
